name: reflect_metadata
description: >
  Simple Runtime Metadata Reflection API
version: 1.0.0
homepage: https://github.com/copydog/reflect_metadata.dart
author: shallow <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  reflectable: any

dev_dependencies:
  benchmark_harness: ^1.0.5
  pedantic: ^1.7.0
  test: ^1.6.0
